# Generated by Django 5.1.5 on 2025-02-05 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Unknown Company', max_length=255)),
                ('name', models.CharField(blank=True, default='Default Lead', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, default='Default Industry', max_length=255, null=True)),
                ('location', models.CharField(blank=True, default='Default Location', max_length=255, null=True)),
                ('status', models.CharField(default='New', max_length=100)),
                ('date_generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Default Company Name', max_length=255)),
                ('company_website', models.URLField(blank=True, default='http://default.com', null=True)),
                ('contact_name', models.CharField(default='Name', max_length=255)),
                ('contact_email', models.EmailField(default='example@domain.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='1234567890', max_length=20, null=True)),
                ('product_name', models.CharField(default='Default Product', max_length=255)),
                ('product_description', models.TextField(default='Default description of the product')),
                ('key_features', models.TextField(default='Default key features')),
                ('primary_use_cases', models.TextField(default='Default use cases')),
                ('has_api', models.BooleanField(default=False)),
                ('api_documentation_link', models.URLField(blank=True, default='http://default.com', null=True)),
                ('pricing_model', models.CharField(default='Default pricing model', max_length=255)),
                ('sales_cycle_length', models.CharField(blank=True, default='Default cycle length', max_length=255, null=True)),
                ('commission_structure', models.CharField(blank=True, default='Default commission structure', max_length=255, null=True)),
                ('discounts_offers', models.TextField(blank=True, default='No discounts/offers', null=True)),
                ('common_pain_points', models.TextField(default='Not specified')),
                ('marketing_materials', models.TextField(blank=True, default='No materials available', null=True)),
                ('customer_success_stories', models.TextField(blank=True, default='No success stories', null=True)),
                ('onboarding_training', models.TextField(blank=True, default='No onboarding training', null=True)),
                ('top_competitors', models.TextField(blank=True, default='No top competitors', null=True)),
                ('branding_guidelines', models.TextField(blank=True, default='No branding guidelines', null=True)),
                ('additional_info', models.TextField(blank=True, default='No additional info', null=True)),
                ('cost_information', models.CharField(blank=True, default='No cost info', max_length=255, null=True)),
                ('years_in_business', models.IntegerField(blank=True, default=0, null=True)),
                ('funding_info', models.TextField(blank=True, default='No funding info', null=True)),
                ('product_demo_link', models.URLField(blank=True, default='http://default.com', null=True)),
                ('company_description', models.CharField(blank=True, default='Default description', max_length=255, null=True)),
                ('ideal_customer_profile', models.TextField(blank=True, default='Default ideal customer profile', null=True)),
                ('technical_requirements', models.TextField(blank=True, default='Default technical requirements', null=True)),
                ('unique_selling_points', models.TextField(blank=True, default='Default unique selling points', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='Manual Upload', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Default subject', max_length=255)),
                ('body', models.TextField(default='Default body content')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='leads.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.supplier'),
        ),
    ]
