# Generated by Django 5.1.5 on 2025-01-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='timestamp',
            new_name='date_generated',
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='demand_details',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='location',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(blank=True, default='Default Industry', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, default='Default Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, default='Default Lead', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='additional_info',
            field=models.TextField(blank=True, default='No additional info', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='api_documentation_link',
            field=models.URLField(blank=True, default='http://default.com', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branding_guidelines',
            field=models.TextField(blank=True, default='No branding guidelines', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='commission_structure',
            field=models.CharField(blank=True, default='Default commission structure', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='common_pain_points',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_description',
            field=models.CharField(default='Default description', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(default='Default Company Name', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_website',
            field=models.URLField(blank=True, default='http://default.com', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(default='example@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(default='Name', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, default='1234567890', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cost_information',
            field=models.CharField(blank=True, default='No cost info', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='customer_success_stories',
            field=models.TextField(blank=True, default='No success stories', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='discounts_offers',
            field=models.TextField(blank=True, default='No discounts/offers', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='funding_info',
            field=models.TextField(blank=True, default='No funding info', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='has_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ideal_customer_profile',
            field=models.TextField(default='Default ideal customer profile'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='key_features',
            field=models.TextField(default='Default key features'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='marketing_materials',
            field=models.TextField(blank=True, default='No materials available', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='onboarding_training',
            field=models.TextField(blank=True, default='No onboarding training', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pricing_model',
            field=models.CharField(default='Default pricing model', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='primary_use_cases',
            field=models.TextField(default='Default use cases'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_demo_link',
            field=models.URLField(blank=True, default='http://default.com', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_description',
            field=models.TextField(default='Default description of the product'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_name',
            field=models.CharField(default='Default Product', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sales_cycle_length',
            field=models.CharField(blank=True, default='Default cycle length', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='technical_requirements',
            field=models.TextField(default='Default technical requirements'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='top_competitors',
            field=models.TextField(blank=True, default='No top competitors', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='unique_selling_points',
            field=models.TextField(default='Default unique selling points'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='years_in_business',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='body',
            field=models.TextField(default='Default body content'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(default='Default subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.supplier'),
        ),
    ]
