# Generated by Django 5.1.5 on 2025-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_timestamp_lead_date_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_description',
            field=models.CharField(blank=True, default='Default description', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ideal_customer_profile',
            field=models.TextField(blank=True, default='Default ideal customer profile', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='technical_requirements',
            field=models.TextField(blank=True, default='Default technical requirements', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='unique_selling_points',
            field=models.TextField(blank=True, default='Default unique selling points', null=True),
        ),
    ]
