# Generated by Django 5.1.5 on 2025-02-12 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.supplier'),
        ),
    ]
