# Generated by Django 5.1.5 on 2025-02-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_emaillog_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.supplier'),
            preserve_default=False,
        ),
    ]
