# Generated by Django 5.1.5 on 2025-02-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_emaillog_delivered_emaillog_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
